### ISSUE TITLE
Website construction/implementation tracker 

### ISSUE THREAD

**Issue by telepath37** [insightsengineering/nest#11]
Creating this issue as a placeholder to track all iterative design & implementation process for the website construction. 

Comments will be left here to request changes to be made to the website.

**Comment by telepath37** [comment]
Thanks for the quick update! Some follow-up items:

- [ ] For homepage banner - let's use the same color with other subpages
- [ ] for the 5 subpages, reorder them so that it shows as Home, Learn, Blog, Contribute, About on the homepage
- [ ] On the homepage, is it possible to make the NEST logo a bit smaller, and leave some space between the tagline and the subpage headers?
- [ ] For the 'core function' section, the background color could be set as the same with other sections as well?
- [ ] For the timeline, I can see the icon color changes when I hover on them, is it possible to show a popup textbox when hovering/clicking on these icons (to show some detailed text)? In addition, is it feasible to have a scrolling horizontal timeline (to show more than 7 items potentially). I found one template here (https://codepen.io/kentchangdesign/pen/jadgvx) but maybe it's too fancy?

**Comment by telepath37** [comment]
@ProjectsOfMLee for the blog subpage - when we have multiple posts, is it possible to have a search functionality, as well as a filter on the side with year/month? In addition, how could the 3 most recent posts on the blog subpage _automatically_ linked to the main page?
