### ISSUE TITLE
website launch plan

### ISSUE THREAD

**Issue by telepath37** [insightsengineering/nest#18]
We probably will go with a phased website launch plan, i.e. gradually adding more content to it. Here is a draft plan:

**Phase 1 - First Launch** (expected: End of Aug'23)
- [ ] URL (buy from namecheap)
- [ ] one-pager homepage containing: 
  - [ ] video
  - [ ] updated logos
  - [ ] slogan & intro text
  - [ ] product carousel
  - [ ] timeline
  - [ ] operating principles
  - [ ] footer with necessary contact information

**Phase 2** (Expected: Oct'23 or end of PI9)
- [ ] Learn page, including links to 'Get Started' vignettes for rtables, tern, teal, TLG-C
- [ ] Blog page: adding several posts about NEST external presentations/news, link the latest posts back to homepage
- [ ] Contribute page: 
  - [ ] contribute via posting issues (a little gif explaining the process?)
  - [ ] links to technical contribution guideline
- [ ] About page: do we need this? If so, what to show here?

Need to discuss maintenance plan of the website, e.g. we should have one/two people review & update the content periodically.
